version: '3.8'

services:
  enhancement-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enhancement-engine-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      # Default email for demo purposes - can be overridden
      - DEMO_EMAIL=demo@example.com
      # Cache settings
      - CACHE_ENABLED=true
      - CACHE_DIR=/app/data/cache
      # Log level
      - LOG_LEVEL=INFO
    volumes:
      # Persist cache data
      - enhancement_cache:/app/data/cache
      - enhancement_sequences:/app/data/cached_sequences
      - enhancement_logs:/app/logs
      # Mount templates directory for easier development
      - ./templates:/app/templates:ro
      - ./webapp/templates:/app/webapp/templates:ro
    networks:
      - enhancement-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a Redis cache for better performance
  redis:
    image: redis:7-alpine
    container_name: enhancement-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - enhancement-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add Nginx as reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: enhancement-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - enhancement-engine
  #   networks:
  #     - enhancement-network
  #   restart: unless-stopped
  #   profiles:
  #     - production

volumes:
  enhancement_cache:
    driver: local
  enhancement_sequences:
    driver: local
  enhancement_logs:
    driver: local
  redis_data:
    driver: local

networks:
  enhancement-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16